customhost = "database-1.cm7btrohxhxc.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "tengkaideng-employee"
customregion = "us-east-1"
